stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_IMAGE: "docker.io/Sirinemn/stock-management-back"


cache:
  key: maven
  paths:
    - .m2/repository/

before_script:
  - mkdir -p ~/.m2
  - echo "<settings><mirrors><mirror><id>central</id><mirrorOf>*</mirrorOf><url>https://repo.maven.apache.org/maven2/</url></mirror></mirrors></settings>" > ~/.m2/settings.xml

# 1️⃣ Étape de Build
build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

# 2️⃣ Étape de Test
test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn test $MAVEN_OPTS

# 3️⃣ Étape de Déploiement
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "🚀 Construction et push de l'image Docker"
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_TOKEN" docker.io
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
