stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  DOCKER_IMAGE: "registry.gitlab.com/ton-utilisateur/nom-du-projet"

before_script:
  - echo "⚙️ Initialisation de l'environnement..."
  - export PATH=$PATH:/usr/local/maven/bin

cache:
  paths:
    - .m2/repository/

# 1️⃣ Étape de Build
build:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - mvn clean package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

# 2️⃣ Étape de Test
test:
  stage: test
  image: maven:3.8.4-openjdk-17
  script:
    - mvn test $MAVEN_CLI_OPTS

# 3️⃣ Étape de Déploiement
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "🚀 Construction et push de l'image Docker"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
