version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stockmanagement-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build: .
    container_name: stockmanagement-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "8001:8001"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
